const ensureDatabaseExists = require('./ensureDatabaseExists');
const initializeDatabase = require('./initializeDatabase');
const sequelize = require('./sequelize');
const ProductModel = require('./models/ProductModel');

const products = [
  {
    sku: 'APPLE-IP15-128-BLK',
    name: 'Apple iPhone 15 128 GB Preto',
    description: 'Smartphone com tela Super Retina XDR de 6,1 polegadas, câmera principal de 48 MP e conexão USB-C.',
    price: 4499.90,
    category: 'Smartphones',
    stock: 18,
    active: true,
  },
  {
    sku: 'SAMS-S24-256-GRY',
    name: 'Samsung Galaxy S24 256 GB Cinza',
    description: 'Smartphone 5G com tela AMOLED de 6,2 polegadas, câmera tripla e recursos Galaxy AI.',
    price: 3999.00,
    category: 'Smartphones',
    stock: 22,
    active: true,
  },
  {
    sku: 'MOTO-G84-256-BLU',
    name: 'Motorola Moto G84 5G 256 GB Azul',
    description: 'Smartphone com 8 GB de RAM, tela pOLED de 6,5 polegadas e câmera de 50 MP com estabilização óptica.',
    price: 1499.90,
    category: 'Smartphones',
    stock: 31,
    active: true,
  },
  {
    sku: 'LENOVO-IP3-I5-512',
    name: 'Notebook Lenovo IdeaPad 3 Intel Core i5 512 GB SSD',
    description: 'Notebook de 15,6 polegadas com processador Intel Core i5, 8 GB de RAM e SSD de 512 GB.',
    price: 3299.90,
    category: 'Informática',
    stock: 14,
    active: true,
  },
  {
    sku: 'ACER-A515-R7-512',
    name: 'Notebook Acer Aspire 5 Ryzen 7 512 GB SSD',
    description: 'Notebook com tela Full HD de 15,6 polegadas, processador AMD Ryzen 7, 12 GB de RAM e SSD de 512 GB.',
    price: 3899.00,
    category: 'Informática',
    stock: 9,
    active: true,
  },
  {
    sku: 'APPLE-MBA-M2-256',
    name: 'Apple MacBook Air M2 256 GB Cinza-espacial',
    description: 'Notebook com chip Apple M2, tela Liquid Retina de 13,6 polegadas, 8 GB de memória e SSD de 256 GB.',
    price: 7999.90,
    category: 'Informática',
    stock: 7,
    active: true,
  },
  {
    sku: 'LOGI-MXMASTER3S-GRY',
    name: 'Mouse sem Fio Logitech MX Master 3S Grafite',
    description: 'Mouse ergonômico com sensor de 8.000 DPI, rolagem MagSpeed e conexão Bluetooth ou USB Logi Bolt.',
    price: 649.90,
    category: 'Periféricos',
    stock: 26,
    active: true,
  },
  {
    sku: 'REDR-KUMARA-RGB',
    name: 'Teclado Mecânico Redragon Kumara RGB',
    description: 'Teclado gamer compacto no padrão ABNT2, com iluminação RGB e switches mecânicos.',
    price: 289.90,
    category: 'Periféricos',
    stock: 35,
    active: true,
  },
  {
    sku: 'DELL-P2422H-24',
    name: 'Monitor Dell P2422H 23,8 Polegadas Full HD',
    description: 'Monitor IPS Full HD com ajuste de altura, conexões HDMI, DisplayPort e hub USB integrado.',
    price: 1299.90,
    category: 'Monitores',
    stock: 16,
    active: true,
  },
  {
    sku: 'KING-NV2-SSD-1TB',
    name: 'SSD Kingston NV2 NVMe 1 TB',
    description: 'Unidade de armazenamento M.2 2280 PCIe 4.0 NVMe com capacidade de 1 TB.',
    price: 399.90,
    category: 'Armazenamento',
    stock: 42,
    active: true,
  },
  {
    sku: 'JBL-FLIP6-BLK',
    name: 'Caixa de Som Bluetooth JBL Flip 6 Preta',
    description: 'Caixa de som portátil com proteção IP67 contra água e poeira e até 12 horas de reprodução.',
    price: 699.00,
    category: 'Áudio',
    stock: 28,
    active: true,
  },
  {
    sku: 'APPLE-AIRPODS-PRO2',
    name: 'Apple AirPods Pro de 2ª Geração',
    description: 'Fones de ouvido sem fio com cancelamento ativo de ruído, áudio adaptativo e estojo de recarga USB-C.',
    price: 1899.90,
    category: 'Áudio',
    stock: 12,
    active: true,
  },
  {
    sku: 'SONY-WH1000XM5-BLK',
    name: 'Fone de Ouvido Sony WH-1000XM5 Preto',
    description: 'Headphone Bluetooth over-ear com cancelamento de ruído, microfone integrado e bateria de longa duração.',
    price: 2299.00,
    category: 'Áudio',
    stock: 8,
    active: true,
  },
  {
    sku: 'LG-OLED55-C3',
    name: 'Smart TV LG OLED evo C3 55 Polegadas 4K',
    description: 'Televisor OLED 4K com Dolby Vision, taxa de atualização de 120 Hz e sistema webOS.',
    price: 5999.90,
    category: 'TV e Vídeo',
    stock: 6,
    active: true,
  },
  {
    sku: 'ROKU-EXPRESS-FHD',
    name: 'Streaming Player Roku Express Full HD',
    description: 'Dispositivo compacto para reprodução de serviços de streaming em resolução Full HD via HDMI.',
    price: 219.90,
    category: 'TV e Vídeo',
    stock: 47,
    active: true,
  },
  {
    sku: 'AMZN-KINDLE-PW16',
    name: 'Amazon Kindle Paperwhite 16 GB',
    description: 'Leitor digital com tela antirreflexo de 6,8 polegadas, iluminação ajustável e resistência à água.',
    price: 899.90,
    category: 'Leitores Digitais',
    stock: 19,
    active: true,
  },
  {
    sku: 'AMZN-ECHODOT5-BLK',
    name: 'Amazon Echo Dot 5ª Geração Preto',
    description: 'Alto-falante inteligente com Alexa, sensor de temperatura e conectividade Wi-Fi e Bluetooth.',
    price: 429.00,
    category: 'Casa Inteligente',
    stock: 33,
    active: true,
  },
  {
    sku: 'PHIL-RI9252-4L',
    name: 'Airfryer Philips Walita Série 3000 RI9252',
    description: 'Fritadeira elétrica sem óleo com capacidade de 4,1 litros, controle de temperatura e timer.',
    price: 599.90,
    category: 'Eletroportáteis',
    stock: 24,
    active: true,
  },
  {
    sku: 'NESP-ESSENZA-MINI',
    name: 'Cafeteira Nespresso Essenza Mini Preta',
    description: 'Máquina compacta para cafés espresso e lungo, com bomba de alta pressão e desligamento automático.',
    price: 549.90,
    category: 'Eletroportáteis',
    stock: 17,
    active: true,
  },
  {
    sku: 'OSTER-OLIQ610-1400',
    name: 'Liquidificador Oster 1400 Full OLIQ610',
    description: 'Liquidificador de 1.400 W com jarra plástica de 3,2 litros e 15 velocidades.',
    price: 239.90,
    category: 'Eletroportáteis',
    stock: 29,
    active: true,
  },
  {
    sku: 'ELECT-ERB10-ROBO',
    name: 'Aspirador Robô Electrolux ERB10',
    description: 'Aspirador robô 3 em 1 com sensores antiqueda, escovas laterais e bateria recarregável.',
    price: 799.90,
    category: 'Eletrodomésticos',
    stock: 13,
    active: true,
  },
  {
    sku: 'MOND-VTX40-8P',
    name: 'Ventilador de Mesa Mondial Turbo VTX-40-8P',
    description: 'Ventilador de 40 cm com oito pás, três velocidades, oscilação horizontal e inclinação regulável.',
    price: 199.90,
    category: 'Climatização',
    stock: 38,
    active: true,
  },
  {
    sku: 'TRAM-PARIS-6PC',
    name: 'Jogo de Panelas Tramontina Paris 6 Peças',
    description: 'Conjunto de panelas de alumínio com revestimento antiaderente Starflon e cabos antitérmicos.',
    price: 449.90,
    category: 'Cozinha',
    stock: 21,
    active: true,
  },
  {
    sku: 'BRINOX-ITAPEMA-24',
    name: 'Faqueiro Brinox Itaparica 24 Peças',
    description: 'Conjunto de talheres em aço inox para seis pessoas, com facas, garfos, colheres e colheres de chá.',
    price: 189.90,
    category: 'Cozinha',
    stock: 27,
    active: true,
  },
  {
    sku: 'ORTOB-NASA-50X70',
    name: 'Travesseiro Ortobom Nasa Viscoelástico 50 x 70 cm',
    description: 'Travesseiro de espuma viscoelástica com capa removível, desenvolvido para se adaptar ao contorno da cabeça.',
    price: 159.90,
    category: 'Cama, Mesa e Banho',
    stock: 44,
    active: true,
  },
  {
    sku: 'ARNO-ULTRAGLISS-FV',
    name: 'Ferro a Vapor Arno Ultragliss Plus',
    description: 'Ferro de passar com base Durilium AirGlide, vapor vertical e sistema corta-pingos.',
    price: 329.90,
    category: 'Eletroportáteis',
    stock: 20,
    active: true,
  },
  {
    sku: 'NIKE-REV7-MASC-41',
    name: 'Tênis Nike Revolution 7 Masculino Preto 41',
    description: 'Tênis de corrida com cabedal respirável, entressola de espuma e solado de borracha.',
    price: 399.90,
    category: 'Calçados',
    stock: 15,
    active: true,
  },
  {
    sku: 'ADID-GRANDCT2-FEM-37',
    name: 'Tênis Adidas Grand Court 2.0 Feminino Branco 37',
    description: 'Tênis casual inspirado nas quadras, com cabedal sintético e solado de borracha.',
    price: 349.90,
    category: 'Calçados',
    stock: 18,
    active: true,
  },
  {
    sku: 'HAV-TOP-BLK-3940',
    name: 'Chinelo Havaianas Top Preto 39/40',
    description: 'Chinelo unissex de borracha com tiras largas e solado antiderrapante.',
    price: 49.90,
    category: 'Calçados',
    stock: 65,
    active: true,
  },
  {
    sku: 'LEVIS-501-MASC-42',
    name: 'Calça Jeans Levi’s 501 Original Masculina 42',
    description: 'Calça jeans masculina de corte reto, cintura média e fechamento clássico por botões.',
    price: 499.90,
    category: 'Moda',
    stock: 11,
    active: true,
  },
  {
    sku: 'LUPO-MEIA-6P-3943',
    name: 'Kit de Meias Lupo Sport com 6 Pares 39/43',
    description: 'Conjunto de meias esportivas de cano curto em algodão, poliamida e elastano.',
    price: 79.90,
    category: 'Moda',
    stock: 52,
    active: true,
  },
  {
    sku: 'CASIO-DW5600-BLK',
    name: 'Relógio Casio G-Shock DW-5600 Preto',
    description: 'Relógio digital resistente a impactos e à água, com cronômetro, alarme e iluminação eletroluminescente.',
    price: 649.90,
    category: 'Relógios',
    stock: 10,
    active: true,
  },
  {
    sku: 'RAYBAN-RB3025-AVI',
    name: 'Óculos de Sol Ray-Ban Aviator RB3025',
    description: 'Óculos de sol com armação metálica dourada e lentes verdes no formato aviador clássico.',
    price: 899.90,
    category: 'Acessórios',
    stock: 9,
    active: true,
  },
  {
    sku: 'SAMSO-FLIGHT-23KG',
    name: 'Mala de Viagem Samsonite Flight Grande',
    description: 'Mala rígida com rodas duplas de giro 360 graus, cadeado TSA e capacidade para viagens longas.',
    price: 1099.90,
    category: 'Malas e Viagem',
    stock: 8,
    active: true,
  },
  {
    sku: 'BOTI-MALBEC-100',
    name: 'Perfume O Boticário Malbec Desodorante Colônia 100 ml',
    description: 'Fragrância masculina amadeirada inspirada no processo de fabricação de vinhos.',
    price: 229.90,
    category: 'Perfumaria',
    stock: 23,
    active: true,
  },
  {
    sku: 'NATU-TODODIA-400',
    name: 'Hidratante Corporal Natura Tododia Algodão 400 ml',
    description: 'Creme nutritivo desodorante para hidratação diária, com fragrância suave de flor de algodão.',
    price: 74.90,
    category: 'Beleza e Cuidados',
    stock: 36,
    active: true,
  },
  {
    sku: 'LOREAL-GLYCOLIC-200',
    name: 'Shampoo L’Oréal Paris Elseve Glycolic Gloss 200 ml',
    description: 'Shampoo para cabelos opacos e porosos com ácido glicólico, desenvolvido para promover brilho e alinhamento.',
    price: 34.90,
    category: 'Beleza e Cuidados',
    stock: 58,
    active: true,
  },
  {
    sku: 'NEUT-SUNFRESH-F70',
    name: 'Protetor Solar Neutrogena Sun Fresh FPS 70 200 ml',
    description: 'Protetor solar corporal de alta proteção contra raios UVA e UVB, com textura leve e rápida absorção.',
    price: 69.90,
    category: 'Beleza e Cuidados',
    stock: 41,
    active: true,
  },
  {
    sku: 'ORALB-PRO3-ELEC',
    name: 'Escova Dental Elétrica Oral-B Pro Series 3',
    description: 'Escova recarregável com sensor de pressão, temporizador e três modos de limpeza.',
    price: 499.90,
    category: 'Higiene Pessoal',
    stock: 16,
    active: true,
  },
  {
    sku: 'PAMP-CONFORT-M-80',
    name: 'Fralda Pampers Confort Sec Tamanho M 80 Unidades',
    description: 'Fralda descartável infantil com canais de ar, barreiras antivazamento e ajuste flexível.',
    price: 119.90,
    category: 'Bebês',
    stock: 34,
    active: true,
  },
  {
    sku: 'LEGO-CLASSIC-10698',
    name: 'LEGO Classic Caixa Grande de Peças Criativas 10698',
    description: 'Conjunto com 790 peças coloridas, janelas, rodas e ideias para diferentes construções.',
    price: 399.90,
    category: 'Brinquedos',
    stock: 14,
    active: true,
  },
  {
    sku: 'BARB-FASHIONISTAS-194',
    name: 'Boneca Barbie Fashionistas Modelo 194',
    description: 'Boneca articulada com visual moderno, roupa casual e acessórios removíveis.',
    price: 99.90,
    category: 'Brinquedos',
    stock: 25,
    active: true,
  },
  {
    sku: 'HOTW-5PACK-SORT',
    name: 'Kit Hot Wheels com 5 Carrinhos Sortidos',
    description: 'Conjunto com cinco veículos em miniatura na escala 1:64, com modelos e cores variados.',
    price: 79.90,
    category: 'Brinquedos',
    stock: 49,
    active: true,
  },
  {
    sku: 'HASB-MONOPOLY-CLASS',
    name: 'Jogo de Tabuleiro Monopoly Clássico Hasbro',
    description: 'Jogo de negociação de propriedades para dois a seis participantes, indicado para maiores de oito anos.',
    price: 149.90,
    category: 'Jogos',
    stock: 20,
    active: true,
  },
  {
    sku: 'WAP-OUSADA-PLUS2200',
    name: 'Lavadora de Alta Pressão WAP Ousada Plus 2200',
    description: 'Lavadora compacta de 1.500 W com pressão máxima de 1.750 PSI, mangueira e aplicador de detergente.',
    price: 649.90,
    category: 'Ferramentas',
    stock: 12,
    active: true,
  },
  {
    sku: 'BOSCH-GSB450RE-127',
    name: 'Furadeira de Impacto Bosch GSB 450 RE 450 W',
    description: 'Furadeira com velocidade variável, reversível, função de impacto e mandril de 10 mm.',
    price: 299.90,
    category: 'Ferramentas',
    stock: 19,
    active: true,
  },
  {
    sku: 'VONDER-FERR-110PC',
    name: 'Jogo de Ferramentas Vonder com 110 Peças',
    description: 'Maleta com chaves, soquetes, alicates, bits e acessórios para reparos domésticos e manutenção.',
    price: 599.90,
    category: 'Ferramentas',
    stock: 10,
    active: true,
  },
  {
    sku: 'ROYAL-MAXI-AD-10KG',
    name: 'Ração Royal Canin Maxi Adult para Cães 10,1 kg',
    description: 'Alimento seco completo para cães adultos de porte grande, formulado para digestão e saúde articular.',
    price: 399.90,
    category: 'Pet Shop',
    stock: 22,
    active: true,
  },
  {
    sku: 'FURAC-TRANSP-N2',
    name: 'Caixa de Transporte Furacão Pet Número 2',
    description: 'Caixa ventilada para transporte de cães e gatos de pequeno porte, com porta metálica e trava de segurança.',
    price: 129.90,
    category: 'Pet Shop',
    stock: 30,
    active: true,
  },
  {
    sku: 'CALOI-VULCAN-29-M',
    name: 'Bicicleta Caloi Vulcan Aro 29 21 Marchas',
    description: 'Mountain bike com quadro de alumínio, suspensão dianteira, freios a disco mecânicos e 21 velocidades.',
    price: 1899.90,
    category: 'Esporte e Lazer',
    stock: 5,
    active: true,
  },
];

async function seed() {
  try {
    await ensureDatabaseExists();
    await initializeDatabase();
    await ProductModel.bulkCreate(products, { ignoreDuplicates: true });
    console.log('Carga inicial concluída.');
  } catch (error) {
    console.error('Falha ao executar a carga inicial:', error.message);
    process.exitCode = 1;
  } finally {
    await sequelize.close().catch(() => undefined);
  }
}

seed();
